export function mdOptionsFactory(options: MdBuilderOptions): MarkdownBuilderOptions {
    return {
        autoGeneratedComment: 'Auto Generated Below',
        hasAutoGeneratedComment: false,
        tableOfContentTitle: 'Table of Content',
        tableOfContentHeaderLevel: 1,
        ...options
    };
}

export type MdBuilderOptions = Partial<MarkdownBuilderOptions>;

export interface MarkdownBuilderOptions {

    /**
     * Defaults to `false`
     *
     * @type {boolean}
     * @memberof MarkdownBuilderOptions
     */
    hasAutoGeneratedComment: boolean;

    /**
     * Defaults to "Auto Generated Below"
     *
     * @type {string}
     * @memberof MarkdownBuilderOptions
     */
    autoGeneratedComment: string;

    /**
     * Defaults to "Table of Content"
     *
     * @type {string}
     * @memberof MarkdownBuilderOptions
     */
    tableOfContentTitle: string;

    /**
     * Defaults to "1"
     *
     * @type {HeaderLevel}
     * @memberof MarkdownBuilderOptions
     */
    tableOfContentHeaderLevel: HeaderLevel;
}

export class MarkdownTableHeader {
    key: string;
    title: string;
    alignment?: MarkdownTableAlignment;
}

export type MarkdownTableAlignment = 'centered' | 'right' | 'left';

export type HeaderLevel = 1 | 2 | 3 | 4 | 5 | 6;
